#!/bin/bash

my_pid=$$
echo "My process ID is $my_pid"

echo "Running Stage..."
rosrun stage_ros stageros worlds/hospital.world base_scan_1:=scan odom:=pose &
pid = $!
sleep 5s

echo "Running fake_amcl.py"
rosrun fembots fake_amcl.py
pid="$pid $!"

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h

