TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: -0.3
  max_vel_theta: 0.5
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0.4
  escape_vel: -0.25
  acc_lim_theta: 2.5
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  xy_goal_tolerance: 0.20
  holonomic_robot: false
  sim_time: 1.7
  meter_scoring: true
  heading_lookahead: 1.0
  pdist_scale: 0.8
  gdist_scale: 1.0
